const S = {
  wrap: { fontFamily: "'Segoe UI', sans-serif", minHeight: "100vh", background: "#F9FAFB" },
  dash: { display: "grid", gridTemplateColumns: "280px 1fr", minHeight: "100vh" },
  sidebar: { background: "#fff", borderRight: "1px solid #E5E7EB", display: "flex", flexDirection: "column", position: "sticky", top: 0, height: "100vh", overflowY: "auto" },
  sbBrand: { padding: "26px 22px", borderBottom: "1px solid #E5E7EB" },
  logo: { fontSize: 21, fontWeight: 800, letterSpacing: "-0.02em" },
  logoEm: { color: "#2563EB" },
  sbRole: { display: "inline-block", marginTop: 10, fontSize: 13, fontWeight: 700, textTransform: "uppercase", padding: "5px 12px", borderRadius: 20, background: "#EFF6FF", color: "#2563EB" },
  sbNav: { padding: 14, flex: 1 },
  sbLabel: { fontSize: 12, fontWeight: 700, letterSpacing: ".12em", textTransform: "uppercase", color: "#9CA3AF", padding: "0 10px", margin: "18px 0 8px", display: "block" },
  sbLink: { display: "flex", alignItems: "center", gap: 12, padding: "14px 15px", borderRadius: 10, fontSize: 16, fontWeight: 500, color: "#4B5563", textDecoration: "none", marginBottom: 4 },
  sbLinkActive: { display: "flex", alignItems: "center", gap: 12, padding: "14px 15px", borderRadius: 10, fontSize: 16, fontWeight: 700, color: "#2563EB", background: "#EFF6FF", textDecoration: "none", marginBottom: 4 },
  sbBadge: { marginLeft: "auto", background: "#2563EB", color: "#fff", fontSize: 12, fontWeight: 700, padding: "3px 9px", borderRadius: 10 },
  sbUser: { padding: "18px 22px", borderTop: "1px solid #E5E7EB", display: "flex", alignItems: "center", gap: 12 },
  av: { width: 42, height: 42, borderRadius: "50%", background: "linear-gradient(135deg,#2563EB,#1D4ED8)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 700, fontSize: 16, flexShrink: 0 },
  main: { padding: "30px" },
  topRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24, flexWrap: "wrap", gap: 12 },
  pageTitle: { fontSize: 28, fontWeight: 800, color: "#111827" },
  badge: { background: "#2563EB", color: "#fff", fontSize: 13, fontWeight: 700, padding: "4px 12px", borderRadius: 20 },
  btnToutLire: { background: "#F3F4F6", color: "#4B5563", border: "none", borderRadius: 9, padding: "9px 16px", fontSize: 14, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  card: { background: "#fff", border: "1px solid #E5E7EB", borderRadius: 14, marginBottom: 18 },
  // une notification
  notifItem: { display: "flex", gap: 14, padding: "16px 20px", borderBottom: "1px solid #F3F4F6", cursor: "pointer", transition: "background .1s" },
  notifItemNonLue: { display: "flex", gap: 14, padding: "16px 20px", borderBottom: "1px solid #F3F4F6", background: "#F0F7FF", cursor: "pointer" },
  notifIconWrap: { width: 40, height: 40, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, flexShrink: 0 },
  notifCorps: { flex: 1 },
  notifTitre: { fontSize: 15, fontWeight: 700, color: "#111827", marginBottom: 3 },
  notifMsg: { fontSize: 14, color: "#6B7280", lineHeight: 1.5, marginBottom: 4 },
  notifDate: { fontSize: 12, color: "#9CA3AF" },
  dotNonLu: { width: 8, height: 8, borderRadius: "50%", background: "#2563EB", flexShrink: 0, marginTop: 6 },
  btnSuppr: { background: "none", border: "none", cursor: "pointer", color: "#9CA3AF", fontSize: 16, padding: "4px 6px", flexShrink: 0 },
  empty: { textAlign: "center", padding: "48px 20px", color: "#9CA3AF" },
  emptyIcon: { fontSize: 36, marginBottom: 12 },
};

export default S;
