const S = {
  wrap: { fontFamily: "'Segoe UI', sans-serif", minHeight: "100vh", background: "#F9FAFB" },
  dash: { display: "grid", gridTemplateColumns: "260px 1fr", minHeight: "100vh" },
  sidebar: { background: "#fff", borderRight: "1px solid #E5E7EB", display: "flex", flexDirection: "column", position: "sticky", top: 0, height: "100vh", overflowY: "auto" },
  sbBrand: { padding: "24px 22px", borderBottom: "1px solid #E5E7EB" },
  logo: { fontSize: 22, fontWeight: 800, letterSpacing: "-0.02em" },
  logoEm: { color: "#2563EB" },
  sbRole: { display: "inline-block", marginTop: 8, fontSize: 13, fontWeight: 700, textTransform: "uppercase", padding: "5px 13px", borderRadius: 20, background: "#ECFDF5", color: "#059669" },
  sbNav: { padding: 14, flex: 1 },
  sbLabel: { fontSize: 12, fontWeight: 700, letterSpacing: ".12em", textTransform: "uppercase", color: "#9CA3AF", padding: "0 10px", margin: "18px 0 6px", display: "block" },
  sbLink: { display: "flex", alignItems: "center", gap: 12, padding: "13px 14px", borderRadius: 9, fontSize: 17, fontWeight: 500, color: "#4B5563", textDecoration: "none", marginBottom: 2 },
  sbLinkActive: { display: "flex", alignItems: "center", gap: 12, padding: "13px 14px", borderRadius: 9, fontSize: 17, fontWeight: 600, color: "#2563EB", background: "#EFF6FF", textDecoration: "none", marginBottom: 2 },
  sbBadge: { marginLeft: "auto", background: "#2563EB", color: "#fff", fontSize: 12, fontWeight: 700, padding: "2px 8px", borderRadius: 10 },
  sbUser: { padding: "18px 22px", borderTop: "1px solid #E5E7EB", display: "flex", alignItems: "center", gap: 12 },
  av: { width: 40, height: 40, borderRadius: "50%", background: "linear-gradient(135deg,#059669,#0891B2)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 700, fontSize: 16, flexShrink: 0 },
  main: { padding: "30px 30px" },
  pageTitle: { fontSize: 34, fontWeight: 800, color: "#111827", marginBottom: 8 },
  pageSub: { fontSize: 18, color: "#6B7280", marginBottom: 24 },
  stats: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 16, marginBottom: 24 },
  statAccent: { background: "#059669", borderRadius: 14, padding: "20px 22px" },
  stat: { background: "#fff", border: "1px solid #E5E7EB", borderRadius: 14, padding: "20px 22px" },
  statLabelW: { fontSize: 13, fontWeight: 700, color: "rgba(255,255,255,.78)", textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8 },
  statLabel: { fontSize: 13, fontWeight: 700, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8 },
  statValW: { fontSize: 36, fontWeight: 800, color: "#fff" },
  statVal: { fontSize: 36, fontWeight: 800, color: "#111827" },
  card: { background: "#fff", border: "1px solid #E5E7EB", borderRadius: 14, padding: "22px 24px", marginBottom: 18 },
  cardTitle: { fontSize: 20, fontWeight: 800, marginBottom: 16, display: "flex", alignItems: "center", justifyContent: "space-between" },
  cardDesc: { fontSize: 17, color: "#6B7280", marginBottom: 14, lineHeight: 1.7 },
  successMsg: { background: "#ECFDF5", border: "1px solid #A7F3D0", color: "#059669", borderRadius: 10, padding: "13px 16px", fontSize: 16, marginBottom: 16 },
  errorMsg: { background: "#FEF2F2", border: "1px solid #FCA5A5", color: "#DC2626", borderRadius: 10, padding: "13px 16px", fontSize: 16, marginBottom: 16 },
  empty: { textAlign: "center", padding: "24px", color: "#9CA3AF", fontSize: 16 },
  navSemaine: { display: "flex", alignItems: "center", gap: 12, marginBottom: 14, flexWrap: "wrap" },
  navBtn: { background: "#fff", border: "1px solid #E5E7EB", borderRadius: 8, padding: "9px 15px", fontSize: 15, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", color: "#374151" },
  semaineTitre: { fontSize: 18, fontWeight: 700, color: "#111827", flex: 1 },
  agendaWrap: { background: "#fff", border: "1px solid #E5E7EB", borderRadius: 14, overflow: "auto", marginBottom: 18 },
  agendaTable: { width: "100%", borderCollapse: "collapse", minWidth: 640 },
  thHeure: { padding: "12px 6px", fontSize: 13, fontWeight: 700, color: "#9CA3AF", background: "#F9FAFB", borderBottom: "1px solid #E5E7EB", borderRight: "1px solid #E5E7EB", width: 65, textAlign: "center" },
  thJour: { padding: "12px 6px", fontSize: 14, fontWeight: 700, color: "#374151", background: "#F9FAFB", borderBottom: "1px solid #E5E7EB", borderRight: "1px solid #F3F4F6", textAlign: "center" },
  thJourAujourd: { padding: "12px 6px", fontSize: 14, fontWeight: 700, color: "#2563EB", background: "#EFF6FF", borderBottom: "2px solid #2563EB", borderRight: "1px solid #F3F4F6", textAlign: "center" },
  tdHeure: { padding: "8px 5px", fontSize: 13, color: "#9CA3AF", background: "#F9FAFB", borderBottom: "1px solid #F3F4F6", borderRight: "1px solid #E5E7EB", textAlign: "center", fontWeight: 600 },
  tdCell: { padding: 4, borderBottom: "1px solid #F3F4F6", borderRight: "1px solid #F3F4F6", textAlign: "center", verticalAlign: "top", minHeight: 34 },
  creneauDispo: { background: "#EFF6FF", border: "1px solid #BFDBFE", borderRadius: 6, padding: "6px 7px", fontSize: 13, color: "#1D4ED8", fontWeight: 600, marginBottom: 2, cursor: "pointer", textAlign: "left" },
  creneauSelectionne: { background: "#059669", border: "1px solid #059669", borderRadius: 6, padding: "6px 7px", fontSize: 13, color: "#fff", fontWeight: 700, marginBottom: 2, cursor: "pointer", textAlign: "left" },
  label: { fontSize: 16, fontWeight: 700, color: "#374151", display: "block", marginBottom: 8 },
  input: { width: "100%", padding: "12px 14px", borderRadius: 8, border: "1px solid #D1D5DB", fontSize: 16, fontFamily: "inherit", boxSizing: "border-box", marginBottom: 14 },
  select: { width: "100%", padding: "12px 14px", borderRadius: 8, border: "1px solid #D1D5DB", fontSize: 16, fontFamily: "inherit", boxSizing: "border-box", marginBottom: 14, background: "#fff" },
  dureeRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 14 },
  dureeBtn: { width: 38, height: 38, borderRadius: 8, border: "1px solid #D1D5DB", background: "#F3F4F6", fontSize: 20, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "inherit", color: "#374151" },
  dureeVal: { minWidth: 74, textAlign: "center", fontSize: 18, fontWeight: 800, color: "#111827" },
  heureFinBox: { padding: "12px 14px", borderRadius: 8, background: "#EFF6FF", color: "#2563EB", fontWeight: 800, textAlign: "center", marginBottom: 14, fontSize: 18 },
  btnPrimary: { background: "#059669", color: "#fff", border: "none", borderRadius: 10, padding: "13px 24px", fontSize: 16, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  sessionCard: { background: "#F9FAFB", border: "1px solid #E5E7EB", borderRadius: 10, padding: 15, marginBottom: 10 },
  sessionTitle: { fontSize: 17, fontWeight: 700, color: "#111827", marginBottom: 5 },
  sessionMeta: { fontSize: 15, color: "#6B7280", lineHeight: 1.6 },
  g2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 16 },
  pillPending: { fontSize: 12, fontWeight: 700, padding: "3px 9px", borderRadius: 12, background: "#FEF9C3", color: "#92400E", display: "inline-block" },
  pillAccepted: { fontSize: 12, fontWeight: 700, padding: "3px 9px", borderRadius: 12, background: "#ECFDF5", color: "#065F46", display: "inline-block" },
  pillRefused: { fontSize: 12, fontWeight: 700, padding: "3px 9px", borderRadius: 12, background: "#FEF2F2", color: "#991B1B", display: "inline-block" },
  pillReported: { fontSize: 12, fontWeight: 700, padding: "3px 9px", borderRadius: 12, background: "#EFF6FF", color: "#1D4ED8", display: "inline-block" },
};

export default S;
