const S = {
  wrap: { fontFamily: "'Segoe UI', sans-serif", minHeight: "100vh", background: "#F9FAFB" },
  logo: { fontSize: 24, fontWeight: 800, letterSpacing: "-0.02em" },
  logoEm: { color: "#2563EB" },
  dash: { display: "grid", gridTemplateColumns: "280px 1fr", minHeight: "100vh" },
  sidebar: { background: "#fff", borderRight: "1px solid #E5E7EB", display: "flex", flexDirection: "column", position: "sticky", top: 0, height: "100vh", overflowY: "auto" },
  sbBrand: { padding: "26px 22px", borderBottom: "1px solid #E5E7EB" },
  sbRole: { display: "inline-block", marginTop: 10, fontSize: 13, fontWeight: 700, letterSpacing: ".08em", textTransform: "uppercase", padding: "5px 12px", borderRadius: 20, background: "#ECFDF5", color: "#059669" },
  sbNav: { padding: 14, flex: 1 },
  sbLabel: { fontSize: 12, fontWeight: 700, letterSpacing: ".12em", textTransform: "uppercase", color: "#9CA3AF", padding: "0 10px", margin: "18px 0 8px", display: "block" },
  sbLink: { display: "flex", alignItems: "center", gap: 12, padding: "14px 15px", borderRadius: 10, fontSize: 17, fontWeight: 500, color: "#4B5563", textDecoration: "none", marginBottom: 4 },
  sbLinkActive: { display: "flex", alignItems: "center", gap: 12, padding: "14px 15px", borderRadius: 10, fontSize: 17, fontWeight: 700, color: "#2563EB", background: "#EFF6FF", textDecoration: "none", marginBottom: 4 },
  sbBadge: { marginLeft: "auto", background: "#2563EB", color: "#fff", fontSize: 12, fontWeight: 700, padding: "3px 9px", borderRadius: 10 },
  sbUser: { padding: "18px 22px", borderTop: "1px solid #E5E7EB", display: "flex", alignItems: "center", gap: 12 },
  av: { width: 42, height: 42, borderRadius: "50%", background: "linear-gradient(135deg,#059669,#0891B2)", display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontWeight: 700, fontSize: 16, flexShrink: 0 },
  main: { padding: "30px 30px" },
  topBar: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, marginBottom: 22, flexWrap: "wrap" },
  smallTitle: { fontSize: 28, fontWeight: 800, color: "#111827", margin: 0 },
  smallSub: { fontSize: 17, color: "#6B7280", marginTop: 8, lineHeight: 1.7, maxWidth: "920px" },
  infoBanner: { background: "#EFF6FF", border: "1px solid #BFDBFE", color: "#1D4ED8", borderRadius: 14, padding: "16px 18px", fontSize: 16, lineHeight: 1.7, marginBottom: 20 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18, marginBottom: 18 },
  card: { background: "#fff", border: "1px solid #E5E7EB", borderRadius: 16, padding: "22px 24px" },
  cardTitle: { fontSize: 18, fontWeight: 800, color: "#111827", marginBottom: 14 },
  cardDesc: { fontSize: 16, color: "#6B7280", lineHeight: 1.7, marginBottom: 16 },
  summaryBox: { background: "#F9FAFB", border: "1px solid #E5E7EB", borderRadius: 12, padding: 14, marginBottom: 12 },
  summaryLabel: { fontSize: 12, color: "#9CA3AF", marginBottom: 6 },
  summaryValue: { fontSize: 16, fontWeight: 700, color: "#111827", lineHeight: 1.6 },
  starsRow: { display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 18 },
  starBtn: { width: 52, height: 52, borderRadius: "50%", border: "1.5px solid #E5E7EB", background: "#fff", fontSize: 24, cursor: "pointer" },
  starBtnActive: { width: 52, height: 52, borderRadius: "50%", border: "1.5px solid #2563EB", background: "#EFF6FF", color: "#2563EB", fontSize: 24, cursor: "pointer" },
  field: { marginBottom: 16 },
  label: { display: "block", fontSize: 16, fontWeight: 700, color: "#374151", marginBottom: 8 },
  select: { width: "100%", padding: "13px 14px", borderRadius: 10, border: "1.5px solid #E5E7EB", fontFamily: "inherit", fontSize: 15, outline: "none", background: "#fff", boxSizing: "border-box" },
  textarea: { width: "100%", minHeight: 140, padding: "13px 14px", borderRadius: 10, border: "1.5px solid #E5E7EB", fontFamily: "inherit", fontSize: 16, outline: "none", background: "#fff", boxSizing: "border-box", resize: "vertical" },
  btnRow: { display: "flex", gap: 10, flexWrap: "wrap", marginTop: 10 },
  btn: { display: "inline-flex", alignItems: "center", justifyContent: "center", fontFamily: "inherit", fontSize: 15, fontWeight: 700, padding: "11px 16px", borderRadius: 10, border: "none", cursor: "pointer", textDecoration: "none" },
  btnPrimary: { background: "#2563EB", color: "#fff" },
  btnGhost: { background: "#F3F4F6", color: "#4B5563" },
  empty: { textAlign: "center", padding: "30px", color: "#9CA3AF" },
  successMsg: { background: "#ECFDF5", border: "1px solid #A7F3D0", color: "#059669", borderRadius: 8, padding: "12px 16px", fontSize: 15, marginBottom: 16 },
};

export default S;
